# Generated by Django 6.0.3 on 2026-03-17 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='unit_cost',
            new_name='cost_at_purchase',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='order_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='is_received',
            new_name='received',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='subtotal',
            new_name='price_at_sale',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='espalda',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='muslo',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='voice_command_raw',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='bota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='espalda_ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='hombros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='observations',
            field=models.TextField(blank=True, help_text='Notas sobre postura o preferencias'),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='talle_delantero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='voice_metadata',
            field=models.JSONField(blank=True, help_text='Parámetros extraídos por IA de la voz', null=True),
        ),
        migrations.AlterField(
            model_name='measurementsheet',
            name='biceps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurementsheet',
            name='cadera',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurementsheet',
            name='cintura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurementsheet',
            name='cuello',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurementsheet',
            name='largo_manga',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurementsheet',
            name='largo_pantalon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurementsheet',
            name='pecho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurementsheet',
            name='puño',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurementsheet',
            name='tiro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW', 'Materia Prima'), ('FINISHED', 'Producto Terminado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(help_text='metros, unidades, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_custom_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finished_product', models.ForeignKey(limit_choices_to={'product_type': 'FINISHED'}, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='core.product')),
                ('raw_material', models.ForeignKey(limit_choices_to={'product_type': 'RAW'}, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
