# Generated by Django 6.0.3 on 2026-03-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_unit_cost_purchaseitem_cost_at_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text="Datos específicos: {color: 'azul', talla: '40'}"),
        ),
    ]
