# Generated by Django 6.0.3 on 2026-03-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='field_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
