# Generated by Django 6.0.3 on 2026-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_image_product_is_active_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
