# Generated by Django 6.0.3 on 2026-03-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementsheet',
            name='biceps',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='bota',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='cuello',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='espalda_ancho',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='hombros',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='largo_manga',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='largo_pantalon',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='pecho',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='puño',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='talle_delantero',
        ),
        migrations.RemoveField(
            model_name='measurementsheet',
            name='tiro',
        ),
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='abdomen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='alto_busto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='caja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='chaleco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='detalle_chaleco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='detalle_falda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='detalle_pantalon',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='detalle_saco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='entalle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='entre_pierna',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='espalda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='hombro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='largo_falda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='manga',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='modelo_detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='muslo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='pf_largo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='rodilla',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='sc_largo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='torax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurementsheet',
            name='vota_pie',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
